Management/urls.py
from django.urls import path
from . import views 



app_name = "Management"
urlpatterns=[
    path("", views.index, name="Home"),
    path("fav/", views.view_fav, name="View_Favourite"),
    path("addfav/", views.add_fav, name="Add_Favourite"),
    path("addcompl/", views.add_complaint, name="Add_Complaint"),
    path("compl/", views.view_complaint, name="View_Complaint"),
    path('update_complaint/<int:complaint_id>/', views.update_complaint, name='Update_Complaint'),
    path('delete_complaint/<int:complaint_id>/', views.delete_complaint, name='Delete_Complaint'),
    path("search/", views.search, name="Search"),
    path("signup/", views.sign_up, name="Sign_Up"),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
]

Payroll_Management_System/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('Management.urls')),
    path('', include('Management.urls')),
]

Management/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
    Name = models.CharField(max_length=64)
    Email = models.CharField(max_length=64)
    Password = models.CharField(max_length=64)
    Position = models.CharField(max_length=64)
    Salary = models.IntegerField()


    def __str__(self):
        return f"{self.id}: {self.Name} is {self.Position} with salary of {self.Salary}. Email:{self.Email} and Password:{self.Password}"

class Complaint(models.Model):
    author = models.CharField(max_length=100)
    email = models.EmailField()
    complaint_type = models.CharField(max_length=100)
    subject = models.CharField(max_length=200)
    message = models.TextField()

    def __str__(self):
        return f"{self.id}: {self.author} - {self.complaint_type} - {self.subject}"

Management/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django import forms
from django.urls import reverse
from .models import Employee, Complaint
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect

#Adding Favorite List
favorites = []

#Adding Complaint List
complaint_author = []
complaint_email = []
complaint_type = []
complaint_subject = []
complaint_message = []

class BaseUserForm(forms.Form):
    Email = forms.EmailField(label="Your Email:", max_length=64)
    Password = forms.CharField(label="Password", max_length=64)

class NewFavForm(forms.Form):
    new_favorite = forms.CharField(label="New Favorite", required="True")

class NewComplaintForm(forms.Form):
    name = forms.CharField(label="Your name:", max_length=100, required="True")
    sender = forms.EmailField(label="Your Email:", required="True")
    c_type = forms.CharField(label="Complaint Type:", required="True")
    subject = forms.CharField(label="Subject:", min_length=10, required="True")
    message = forms.CharField(label="Message:", max_length=300, required="True")

class NewSearchForm(forms.Form):
    query = forms.CharField(label="Employee Name:", max_length=100, required="True")

class NewSignupForm(forms.Form):
    Name = forms.CharField(label="Your Name:",max_length=64)
    Email = forms.EmailField(label="Your Email:",max_length=64)
    Password = forms.CharField(label="Password",max_length=64)
    Position = forms.CharField(label="Your Position",max_length=64)
    Salary = forms.IntegerField(label="Your Salary:")

class LoginForm(AuthenticationForm):
    Email = forms.EmailField(label="Your Email:", max_length=64)
    Password = forms.CharField(label="Password", max_length=64)
class UpdateComplaintForm(forms.ModelForm):
    class Meta:
        model = Complaint
        fields = ['author', 'email', 'complaint_type', 'subject', 'message']
# Create your views here.
def index(request):
    return render(request, "Management/index.html", {
        "favorites": favorites
    })
@login_required
def view_fav(request):
    return render(request, "Management/favourite.html", {
        "favorites": favorites
    })
@login_required
def add_fav(request):
    if request.method == "POST":
        form = NewFavForm(request.POST)
        if form.is_valid():
            new_favorite = form.cleaned_data["new_favorite"]
            favorites.append(new_favorite)
            return HttpResponseRedirect(reverse("Management:Add_Favourite"))
        else:
            return render(request, "Management/add_favourite.html", {
                "form": form,
                "favorites": favorites
            })
    
    return render(request, "Management/add_favourite.html", {
        "form": NewFavForm(),
        "favorites": favorites
    })

def add_complaint(request):
    if request.method == "POST":
        form = NewComplaintForm(request.POST)
        if form.is_valid():
            # Save the complaint to the database
            complaint = Complaint(
                author=form.cleaned_data["name"],
                email=form.cleaned_data["sender"],
                complaint_type=form.cleaned_data["c_type"],
                subject=form.cleaned_data["subject"],
                message=form.cleaned_data["message"]
            )
            complaint.save()
            return HttpResponseRedirect(reverse("Management:View_Complaint"))
        else:
            error_message = "Invalid form submission. Please check your input."
            return render(request, "Management/add_complaint.html", {
                "form": form,
                "error_message": error_message,
                "favorites": favorites
            })

    return render(request, "Management/add_complaint.html", {
        "form": NewComplaintForm(),
        "favorites": favorites
    })

@login_required
def view_complaint(request):
    complaints = Complaint.objects.all()
    return render(request, "Management/complaint.html", {
        "Complaint": complaints,
        "favorites": favorites
    })
@login_required
def update_complaint(request, complaint_id):
    complaint = get_object_or_404(Complaint, id=complaint_id)
    if request.method == "POST":
        form = UpdateComplaintForm(request.POST, instance=complaint)
        if form.is_valid():
            form.save()
            return redirect("Management:View_Complaint")
    else:
        form = UpdateComplaintForm(instance=complaint)

    return render(request, "Management/update_complaint.html", {
        "form": form,
        "complaint_id": complaint_id,
        "favorites": favorites
    })

@login_required
def delete_complaint(request, complaint_id):
    complaint = get_object_or_404(Complaint, id=complaint_id)
    if request.method == "POST":
        complaint.delete()
        return redirect("Management:View_Complaint")

    return render(request, "Management/delete_complaint.html", {
        "complaint": complaint,
        "favorites": favorites
    })

@login_required
def search(request):
    result = "NONE"
    if request.method == "POST":
        form = NewSearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data["query"]
            result = Employee.objects.filter(Name__icontains=query)
            return render(request, "Management/search.html", {
                "form": form,
                "result": result,
                "method": request.method,
                "favorites": favorites
            })
        else:
            error_message = "Invalid form submission. Please check your input."
            return render(request, "Management/search.html", {
                "result": result,
                "form": form,
                "error_message": error_message,
                "method": request.method,
                "favorites": favorites
            })

    return render(request, "Management/search.html", {
        "result": result,
        "form": NewSearchForm(),
        "method": request.method,
        "favorites": favorites
    })

def sign_up(request):
    if request.method == "POST":
        form = NewSignupForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["Name"]
            email = form.cleaned_data["Email"]
            password = form.cleaned_data["Password"]
            position = form.cleaned_data["Position"]
            salary = form.cleaned_data["Salary"]
            new_employee = Employee(Name= name, Email= email, Password= password, Position= position, Salary= salary)
            new_employee.save()
            return HttpResponseRedirect(reverse("Management:Sign_Up"))
        else:
            return render(request, "Management/signup.html", {
                "form": form,
                "favorites": favorites
            })
    
    return render(request, "Management/signup.html", {
        "form": NewSignupForm(),
        "favorites": favorites
    })

def login_user(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')  # Assuming you're using username to authenticate
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse("Management:Home")) 
            else:
                error_message = "Invalid login credentials. Please try again."
                return render(request, "Management/login.html", {"form": form, "error_message": error_message})
        else:
            error_message = "Invalid form submission. Please check your input."
            return render(request, "Management/login.html", {"form": form, "error_message": error_message})

    form = AuthenticationForm()  # Create a new instance of the form for GET requests
    return render(request, "Management/login.html", {"form": form})

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse("Management:login"))

Management/templates/Management/add_complaint.html
{% extends "Management/layout.html" %}

{% block title %} New Complaint {% endblock title %}



{% block body %}
<h1>Add a new Complaint</h1>
<form action="{% url 'Management:Add_Complaint' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>
</div>
<div class="repoContainer">
    <a href="{% url 'Management:View_Complaint' %}">View all complaints</a>
{% endblock body%}

Management/templates/Management/add_favourite.html
{% extends "Management/layout.html" %}

{% block title %} Add Favourites {% endblock title %}

{% block body %}
    <h1>Add Favorites</h1>
    <form action="{% url 'Management:Add_Favourite' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <div class="container">
        <a href="{% url 'Management:View_Favourite' %}">View Tasks</a>
    </div>
{% endblock %}

Management/templates/Management/complaint.html
<!-- management/templates/Management/complaint.html -->

{% extends "Management/layout.html" %}

{% block title %} Complaints {% endblock title %}

{% block body %}
  <h4>All Complaints</h4>
            <table id="code" style="width: 100%; border-collapse: collapse;">
              <tr>
                <th style="width: 15%;">Name</th>
                <th style="width: 15%;">Email</th>
                <th style="width: 15%;">Complaint Type</th>
                <th style="width: 20%;">Complaint Subject</th>
                <th style="width: 30%;">Complaint Message</th>
                <th style="width: 5%;">Actions</th>
              </tr>
              {% for comp in Complaint %}
            <tr>
                <td>{{ comp.author }}</td>
                <td>{{ comp.email }}</td>
                <td>{{ comp.complaint_type }}</td>
                <td>{{ comp.subject }}</td>
                <td>{{ comp.message }}</td>
                <td>
                    <a href="{% url 'Management:Update_Complaint' complaint_id=comp.id %}">Update</a>
                    <a href="{% url 'Management:Delete_Complaint' complaint_id=comp.id %}">Delete</a>
                </td>
            
              {% endfor %}
            </table>
{% endblock body %}
{% block sec_body %}
  <a href="{% url 'Management:Add_Complaint' %}" style="position: relative;">Add a New Complaint</a>
{% endblock sec_body %}

Management/templates/Management/delete_complaint.html
{% extends "Management/layout.html" %}

{% block title %} Delete Complaint {% endblock title %}

{% block body %}
    <h1>Delete Complaint</h1>
    <form method="post" action="">
        {% csrf_token %}
        <p>Are you sure you want to delete this complaint?</p>
        <button type="submit">Delete</button>
    </form>
{% endblock body %}

Management/templates/Management/favourite.html
{% extends "Management/layout.html" %}

{% block title %} View Favourite {% endblock title %}

{% block body %}
<h1>Favorites</h1>
<div class="skills">
    <ul>
        {% for fav in favorites %}
            <span>{{ fav }}</span>
            {% empty %}
            <p>No Such Favorites</p>
        {% endfor %}
    </ul>
</div>
    <a href="{% url 'Management:Add_Favourite' %}">Add a New Favourite</a>
{% endblock body %}

Management/templates/Management/index.html
{% extends "Management/layout.html" %}

{% block title %} Home Page {% endblock title %}



{% block body %}
<h1>Features:</h1>
<a href="/admin/" class="repoCard" target="_blank" rel="noopener noreferrer">
   <div class="repoTitle">Login</div>
   <p>Login for Admins</p>
   <div><span>Login</span><span>Admin</span></div>
</a>
<a href="{% url 'Management:Sign_Up' %}" class="repoCard" rel="noopener noreferrer">
    <div class="repoTitle">Signup for Employee</div>
    <p>Employee Register Here!!</p>
    <div><span>Login</span><span>Employee</span></div>
</a>
<a href="{% url 'Management:Add_Complaint' %}" class="repoCard" rel="noopener noreferrer">
   <div class="repoTitle">Report a complaint</div>
   <p>Bug Reports, Complaint Filing System</p>
   <div><span>Form</span><span>Bugs</span></div>
</a>
<a href="{% url 'Management:Add_Favourite' %}" class="repoCard" rel="noopener noreferrer">
   <div class="repoTitle">Add A New Favorite</div>
   <p>Adding a new favorite</p>
   <div><span>Favorite</span><span>Add</span></div>
</a>
<a href="{% url 'Management:Search' %}" class="repoCard" rel="noopener noreferrer">
   <div class="repoTitle">Search an Employee</div>
   <p>Seach Emplyee With there names</p>
   <div><span>Search</span><span>Employee</span></div>
</a>
{% endblock body%}

Management/templates/Management/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/ico" href="{% static 'Management/favicon.ico' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
    <title>
        {% block title %}
        {{ page_title|default:"Payroll Management System" }}
        {% endblock title %}
    </title>
    <link href="{% static 'Management/styles.css' %}" rel="stylesheet">
    <style>
        /* Custom CSS styles for your project outline */
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0; /* Light gray background */
            margin: 0;
            padding: 0;
        }

        .container {
            display: flex;
        }

        .sidebar.user {
            background-color: #454848; /* Teal background color */
            color: #598960;
            width: 250px;
            padding: 20px;
        }

        .main {
            flex-grow: 1;
            background-color: #29362b; /* White background color */
            padding: 20px;
        }

        .avatar img {
            width: 100px;
            height: 100px;
            border-radius: 50%;
            margin: 20px auto;
            display: block;
        }

        h1 {
            font-size: 24px;
            color: #ffffff; /* White text color */
        }

        p {
            font-size: 16px;
            color: #ffffff; /* White text color */
        }

        .buttons {
            background-color: #c9c5c5; /* Darker teal button color */
            color: #385c3b;
            margin-top: 20px;
            text-align: center;
            padding: 10px 20px;
        }

        .button {
            background-color: #0c0c0c; /* Darker teal button color */
            color: #385c3b;
            padding: 10px 20px;
            border: none;
            cursor: pointer;
            font-size: 16px;
            border-radius: 0.5px;
            margin-right: 10px;
        }

        .button:hover {
            background-color: #062c2c; /* Teal button color on hover */
        }

        .developer-info {
            margin-top: 20px;
            background-color: #3f513d; /* Light gray background for developer info */
            padding: 20px;
            border-radius: 5px;
            color: #ffffff; /* White text color */
        }
    </style>
</head>

<body>
    <div id="root">
        <div class="container">
            <div class="sidebar user">
                <a href="{% url 'Management:Home' %}">
                    <div class="avatar shine">
                        <img src="https://res.cloudinary.com/garvitjoshi9/image/upload/v1594407409/Git-Hub/1_4_ebmyhb.jpg"
                            class="profile" alt="Company Picture">
                    </div>
                </a>
                <h1>Payroll Management System</h1>
                <p>A Reliable Management System made for the Elites.</p>
                <div class="button">
                   <span><a href="{% url 'Management:Sign_Up' %}">Siginin</a><br></span> 
                   <span> <a href="{% url 'Management:login' %}">Login</a><br></span> 
                   <span><a href="{% url 'Management:logout' %}">Logout</a></span>
                </div>
            </div>
            <div class="main">
                <div class="repoContainer">
                    {% block body %}
                    {% endblock body %}
                </div>
                <div class="repoContainer">
                    {% block sec_body %}
                    {% endblock sec_body %}
                </div>
            </div>
        </div>
    </div>
    <div class="developer-info">
        <h3>About Developer:</h3>
        <div><i class="fab fa-github-alt"></i><a href="https://github.com/Geethanjali-Allam" target="_blank"
                rel="noopener noreferrer" style="color: inherit;">@GEETHANJALI ALLAM</a></div>
        <div><i class="fas fa-building"></i><a href="https://www.google.com/search?gs_ssp=eJzj4tTP1TcwyigwNzBg9JIuzcssSy0qziypVMhPU8hLLVfISMwtKM7ILEoFAAJBDbg&q=university+of+new+hampshire&rlz=1C1CHBF_enUS1039US1039&oq=university+&gs_lcrp=EgZjaHJvbWUqBwgBEC4YgAQyBggAEEUYOTIHCAEQLhiABDIHCAIQLhiABDIHCAMQLhiABDIGCAQQRRg9MgYIBRBFGEEyBggGEEUYQTIGCAcQRRg80gEJMTczNzNqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8" target="_blank" rel="noopener noreferrer"
                style="color: inherit;">UNIVERSITY OF NEW HAMPSHIRE</a></div>
        <div><i class="fas fa-map-marker-alt"></i><a href="https://www.google.com/search?q=manchester+nh&sca_esv=585281359&rlz=1C1CHBF_enUS1039US1039&sxsrf=AM9HkKnhxyA8PeCMUFb2Tu6J1QcTwkBoUQ%3A1700933664049&ei=IDBiZfO6AtGi5NoPhI-bkAE&gs_ssp=eJzj4tDP1TeoyMgyMmD04s1NzEvOSC0uSS1SyMsAAGOGCDI&oq=manchester+&gs_lp=Egxnd3Mtd2l6LXNlcnAiC21hbmNoZXN0ZXIgKgIIATIKEAAYgAQYigUYQzINEC4YsQMYgAQYigUYQzIKEC4YgAQYigUYQzIKEAAYgAQYigUYQzIKEC4YgAQYigUYQzIKEAAYgAQYigUYQzIKEAAYgAQYigUYQzIKEC4YgAQYigUYQzINEAAYgAQYigUYsQMYQzIQEC4YgAQYigUYxwEYrwEYQzIcEC4YsQMYgAQYigUYQxiXBRjcBBjeBBjgBNgBAkjLOFCVC1iDInABeAGQAQCYAfADoAHjFKoBCTAuNS40LjEuMbgBAcgBAPgBAagCEMICBxAuGOoCGCfCAgcQIxjqAhgnwgINEC4YxwEY0QMY6gIYJ8ICDRAuGMcBGK8BGOoCGCfCAhYQLhiABBiKBRjIAxjqAhi0AhhD2AEBwgIKECMYgAQYigUYJ8ICDRAuGIAEGIoFGLEDGEPiAwQYACBBiAYBugYGCAEQARgIugYGCAIQARgU&sclient=gws-wiz-serp"
                target="_blank" rel="noopener noreferrer" style="color: inherit;">Manchester NH</a></div>
    </div>
</body>

</html>

Management/templates/Management/login.html
{% extends "Management/layout.html" %}

{% block title %} Login as Admin {% endblock title %}

{% block body %}
    <h1>Login</h1>
    {% if error_message %}
        <p>{{ error_message }}</p>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
{% endblock body %}

Management/templates/Management/search.html
{% extends "Management/layout.html" %}

{% block title %} Search {% endblock title %}



{% block body %}
{% if method == "GET" %}
    <h1>Search an Employee</h1>
{% else %}
    <h1>Results</h1>
{% endif %}
<form action="{% url 'Management:Search' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>
</div>
<div class="repoContainer">
    {% if not result and method == "POST" %}
        <p>No Result Found</p>
    {% elif method == "GET" %}
        <p></p>
    {% else %}
        <table id="code" style="position: relative; margin-right: 30px; padding: 15px;border-spacing:30px;">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Position</th>
            </tr>
            {% for r in result %}
                <tr>
                    <td>{{ r.id }}</td>
                    <td>{{ r.Name }}</td>
                    <td>{{ r.Email }}</td>
                    <td>{{ r.Position }}</td>
                </tr>
            {% empty %}
                <td colspan="5" style="text-align: center; color: aqua;">No Result</td>
            {% endfor %}
        </table>
    {% endif %}
{% endblock body%}

Management/templates/Management/signup.html
{% extends "Management/layout.html" %}

{% block title %} SignUp {% endblock title %}

{% block body %}
    <h1>Signup</h1>
    <form action="{% url 'Management:Sign_Up' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <div class="container">
        <a href="{% url 'Management:Home' %}">Home</a>
    </div>
{% endblock %}

Management/templates/Management/update_complaint.html
{% extends "Management/layout.html" %}

{% block title %} Update Complaint {% endblock title %}

{% block body %}
    <h1>Update Complaint</h1>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
{% endblock body %}